[book]
title = "GenAI Attacks Matrix"
authors = ["ZenitySec"]
description = "Documentation for the GenAI Attacks Matrix"
src = "build"

[build]
build-dir = "book"

[output.html]
edit-url-template = "https://github.com/mbrg/genai-attacks/edit/main/{path}"
fold.enable = true
git-repository-url = "https://github.com/mbrg/genai-attacks"
